# #########색상창고
COLORS = {'WHITE': (255, 255, 255),
          'BLACK': (0, 0, 0),
          'GREY': (95, 95, 95),
          'RED':(255, 0, 0),
          'BLUE': (0, 0, 255),
          'GREEN': (0, 255, 0),
          'YELLOW': (255, 255, 0),
          'PURPLE': (110, 0, 255),
          'CYAN': (97, 224, 250),
          'ORANGE': (250, 98, 0)}


BLOCKS = {
    'L' : [('BLACK','BLACK','YELLOW',
            'YELLOW','YELLOW','YELLOW',
            'BLACK','BLACK','BLACK'),
           ('BLACK','YELLOW','BLACK',
            'BLACK','YELLOW','BLACK',
            'BLACK','YELLOW','YELLOW'),
           ('BLACK', 'BLACK', 'BLACK',
            'YELLOW', 'YELLOW', 'YELLOW',
            'YELLOW', 'BLACK', 'BLACK'),
           ('YELLOW', 'YELLOW', 'BLACK',
            'BLACK', 'YELLOW', 'BLACK',
            'BLACK', 'YELLOW', 'BLACK'),],
    'J': [('BLACK', 'PURPLE', 'BLACK',
           'BLACK', 'PURPLE', 'BLACK',
           'PURPLE', 'PURPLE', 'BLACK'),
          ('BLACK', 'BLACK', 'BLACK',
           'PURPLE', 'PURPLE', 'PURPLE',
           'BLACK', 'BLACK', 'PURPLE'),
          ('BLACK', 'PURPLE', 'PURPLE',
           'BLACK', 'PURPLE', 'BLACK',
           'BLACK', 'PURPLE', 'BLACK'),
          ('PURPLE', 'BLACK', 'BLACK',
           'PURPLE', 'PURPLE', 'PURPLE',
           'BLACK', 'BLACK', 'BLACK'), ],
    'T': [('BLACK', 'BLUE', 'BLACK',
           'BLUE', 'BLUE', 'BLACK',
           'BLACK', 'BLUE', 'BLACK'),
          ('BLACK', 'BLACK', 'BLACK',
           'BLUE', 'BLUE', 'BLUE',
           'BLACK', 'BLUE', 'BLACK'),
          ('BLACK', 'BLUE', 'BLACK',
           'BLACK', 'BLUE', 'BLUE',
           'BLACK', 'BLUE', 'BLACK'),
          ('BLACK', 'BLUE', 'BLACK',
           'BLUE', 'BLUE', 'BLUE',
           'BLACK', 'BLACK', 'BLACK'), ],
    'Z': [('BLACK', 'BLACK', 'RED',
           'BLACK', 'RED', 'RED',
           'BLACK', 'RED', 'BLACK'),
          ('RED', 'RED', 'BLACK',
           'BLACK', 'RED', 'RED',
           'BLACK', 'BLACK', 'BLACK'),
          ('BLACK', 'BLACK', 'RED',
           'BLACK', 'RED', 'RED',
           'BLACK', 'RED', 'BLACK'),
          ('RED', 'RED', 'BLACK',
           'BLACK', 'RED', 'RED',
           'BLACK', 'BLACK', 'BLACK')],
    'S': [('BLACK', 'CYAN', 'BLACK',
           'BLACK', 'CYAN', 'CYAN',
           'BLACK', 'BLACK', 'CYAN'),
          ('BLACK', 'CYAN', 'CYAN',
           'CYAN', 'CYAN', 'BLACK',
           'BLACK', 'BLACK', 'BLACK'),
          ('BLACK', 'CYAN', 'BLACK',
           'BLACK', 'CYAN', 'CYAN',
           'BLACK', 'BLACK', 'CYAN'),
          ('BLACK', 'CYAN', 'CYAN',
           'CYAN', 'CYAN', 'BLACK',
           'BLACK', 'BLACK', 'BLACK')],
    'O': [('GREEN', 'GREEN',
           'GREEN', 'GREEN'),
          ('GREEN', 'GREEN',
           'GREEN', 'GREEN'),
          ('GREEN', 'GREEN',
           'GREEN', 'GREEN'),
          ('GREEN', 'GREEN',
           'GREEN', 'GREEN')],
    'I': [('BLACK', 'ORANGE', 'BLACK', 'BLACK',
           'BLACK', 'ORANGE', 'BLACK', 'BLACK',
           'BLACK', 'ORANGE', 'BLACK', 'BLACK',
           'BLACK', 'ORANGE', 'BLACK', 'BLACK',),
          ('BLACK', 'BLACK', 'BLACK', 'BLACK',
           'ORANGE', 'ORANGE', 'ORANGE', 'ORANGE',
           'BLACK', 'BLACK', 'BLACK', 'BLACK',
           'BLACK', 'BLACK', 'BLACK', 'BLACK',),
          ('BLACK', 'BLACK', 'ORANGE', 'BLACK',
           'BLACK', 'BLACK', 'ORANGE', 'BLACK',
           'BLACK', 'BLACK', 'ORANGE', 'BLACK',
           'BLACK', 'BLACK', 'ORANGE', 'BLACK',),
          ('BLACK', 'BLACK', 'BLACK', 'BLACK',
           'BLACK', 'BLACK', 'BLACK', 'BLACK',
           'ORANGE', 'ORANGE', 'ORANGE', 'ORANGE',
           'BLACK', 'BLACK', 'BLACK', 'BLACK',)]}